<a href="https://colab.research.google.com/github/fmuranda/Climate_Science-/blob/main/tutorials/W1D1_ClimateSystemOverview/student/W1D1_Tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/neuromatch/climate-course-content/blob/main/tutorials/W1D1_ClimateSystemOverview/student/W1D1_Tutorial1.ipynb) &nbsp; <a href="https://kaggle.com/kernels/welcome?src=https://raw.githubusercontent.com/neuromatch/climate-course-content/main/tutorials/W1D1_ClimateSystemOverview/student/W1D1_Tutorial1.ipynb" target="_parent"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open in Kaggle"/></a>

# Tutorial 1: Creating DataArrays and Datasets to Assess Global Climate Data

**Week 1, Day 1, Climate System Overview**

**Content creators:** Sloane Garelick, Julia Kent

**Content reviewers:** Yosmely Bermúdez, Katrina Dobson, Younkap Nina Duplex, Danika Gupta, Maria Gonzalez, Will Gregory, Nahid Hasan, Paul Heubel, Sherry Mi, Beatriz Cosenza Muralles, Jenna Pearson, Chi Zhang, Ohad Zivan

**Content editors:** Paul Heubel, Jenna Pearson, Chi Zhang, Ohad Zivan

**Production editors:** Wesley Banfield, Paul Heubel, Jenna Pearson, Konstantine Tsafatinos, Chi Zhang, Ohad Zivan

**Our 2024 Sponsors:** NFDI4Earth and CMIP


## ![project pythia](https://projectpythia.org/_static/images/logos/pythia_logo-blue-rtext.svg)

Pythia credit: Rose, B. E. J., Kent, J., Tyle, K., Clyne, J., Banihirwe, A., Camron, D., May, R., Grover, M., Ford, R. R., Paul, K., Morley, J., Eroglu, O., Kailyn, L., & Zacharias, A. (2023). Pythia Foundations (Version v2023.05.01) https://zenodo.org/record/8065851

## ![CMIP.png](https://github.com/ClimateMatchAcademy/course-content/blob/main/tutorials/Art/CMIP.png?raw=true)


# Tutorial Objectives

*Estimated timing of tutorial:* 20 minutes

As you just learned in the Introduction to Climate video, variations in global climate involve various forcings, feedbacks, and interactions between multiple processes and systems. Because of this complexity, global climate datasets are often very large with multiple dimensions and variables.

One useful computational tool for organizing, analyzing, and interpreting large global datasets is [Xarray](https://xarray.pydata.org/en/v2023.05.0/getting-started-guide/why-xarray.html), an open-source project and Python package that makes working with labeled multi-dimensional arrays simple and efficient.

In this first tutorial, we will use the `DataArray` and `Dataset` objects, which are used to represent and manipulate spatial data, to practice organizing large global climate datasets, and to understand variations in Earth's climate system.


# Setup


Similar to `numpy`, `np`; `pandas`, `pd`; you may often encounter `xarray` imported within a shortened namespace as `xr`.


In [1]:
# imports
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt

In [2]:
# @title Install and import feedback gadget

!pip3 install vibecheck datatops --quiet

from vibecheck import DatatopsContentReviewContainer
def content_review(notebook_section: str):
    return DatatopsContentReviewContainer(
        "",  # No text prompt
        notebook_section,
        {
            "url": "https://pmyvdlilci.execute-api.us-east-1.amazonaws.com/klab",
            "name": "comptools_4clim",
            "user_key": "l5jpxuee",
        },
    ).render()


feedback_prefix = "W1D1_T1"

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 17.8 MB/s eta 0:00:00


In [3]:
# @title Figure Settings
import ipywidgets as widgets  # interactive display

%config InlineBackend.figure_format = 'retina'
plt.style.use(
    "https://raw.githubusercontent.com/neuromatch/climate-course-content/main/cma.mplstyle"
)

In [4]:
# @title Video 1: Introduction to Climate

from ipywidgets import widgets
from IPython.display import YouTubeVideo
from IPython.display import IFrame
from IPython.display import display


class PlayVideo(IFrame):
    def __init__(self, id, source, page=1, width=400, height=300, **kwargs):
        self.id = id
        if source == "Bilibili":
            src = f"https://player.bilibili.com/player.html?bvid={id}&page={page}"
        elif source == "Osf":
            src = f"https://mfr.ca-1.osf.io/render?url=https://osf.io/download/{id}/?direct%26mode=render"
        super(PlayVideo, self).__init__(src, width, height, **kwargs)


def display_videos(video_ids, W=400, H=300, fs=1):
    tab_contents = []
    for i, video_id in enumerate(video_ids):
        out = widgets.Output()
        with out:
            if video_ids[i][0] == "Youtube":
                video = YouTubeVideo(
                    id=video_ids[i][1], width=W, height=H, fs=fs, rel=0
                )
                print(f"Video available at https://youtube.com/watch?v={video.id}")
            else:
                video = PlayVideo(
                    id=video_ids[i][1],
                    source=video_ids[i][0],
                    width=W,
                    height=H,
                    fs=fs,
                    autoplay=False,
                )
                if video_ids[i][0] == "Bilibili":
                    print(
                        f"Video available at https://www.bilibili.com/video/{video.id}"
                    )
                elif video_ids[i][0] == "Osf":
                    print(f"Video available at https://osf.io/{video.id}")
            display(video)
        tab_contents.append(out)
    return tab_contents


video_ids = [("Youtube", "mc-DkvYLdOA"), ("Bilibili", "BV1Th4y1j7SS")]
tab_contents = display_videos(video_ids, W=730, H=410)
tabs = widgets.Tab()
tabs.children = tab_contents
for i in range(len(tab_contents)):
    tabs.set_title(i, video_ids[i][0])
display(tabs)

In [5]:
# @title Submit your feedback
content_review(f"{feedback_prefix}_Intro_to_Climate_Video")

In [6]:
# @markdown
from ipywidgets import widgets
from IPython.display import IFrame

link_id = "4suf5"

print(f"If you want to download the slides: https://osf.io/download/{link_id}/")
IFrame(src=f"https://mfr.ca-1.osf.io/render?url=https://osf.io/{link_id}/?direct%26mode=render%26action=download%26mode=render", width=854, height=480)

If you want to download the slides: https://osf.io/download/4suf5/


In [7]:
# @title Submit your feedback
content_review(f"{feedback_prefix}_Intro_to_Climate_Slides")

# Introducing the `DataArray` and `Dataset`

[Xarray](https://xarray.pydata.org/en/v2023.05.0/getting-started-guide/why-xarray.html) expands on the capabilities on [NumPy](https://numpy.org/doc/stable/user/index.html#user) arrays, providing a lot of streamlined data manipulation. It is similar in that respect to [Pandas](https://pandas.pydata.org/docs/user_guide/index.html#user-guide), but whereas Pandas excels at working with tabular data, Xarray is focused on N-dimensional arrays of data (i.e. grids). Its interface is based largely on the netCDF data model (variables, attributes, and dimensions), but it goes beyond the traditional netCDF interfaces to provide functionality similar to netCDF-java's [Common Data Model (CDM)](https://docs.unidata.ucar.edu/netcdf-java/current/userguide/common_data_model_overview.html).


# Section 1: Creation of a `DataArray` Object

The `DataArray` is one of the basic building blocks of Xarray (see docs [here](http://xarray.pydata.org/en/stable/user-guide/data-structures.html#dataarray)). It provides a `numpy.ndarray`-like object that expands to provide two critical pieces of functionality:

1. Coordinate names and values are stored with the data, making slicing and indexing much more powerful
2. It has a built-in container for attributes

Here we'll initialize a `DataArray` object by wrapping a plain NumPy array, and explore a few of its properties.


## Section 1.1: Generate a Random Numpy Array

For our first example, we'll just [create a random array](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html) of "temperature" data in units of Kelvin:


In [8]:
rand_data = 283 + 5 * np.random.randn(5, 3, 4)
rand_data

array([[[282.9643865 , 282.70292143, 291.51546115, 283.42486548],
        [270.97730145, 289.22798066, 277.52102428, 287.30727676],
        [282.58751063, 286.94690405, 283.28850246, 289.30564317]],

       [[276.71178317, 288.58729864, 275.37034855, 285.25057547],
        [271.41318382, 278.20364763, 280.5031612 , 281.35505081],
        [272.93614756, 282.52331396, 284.16873071, 286.75006634]],

       [[278.78846725, 292.03876694, 285.53074583, 283.29692792],
        [286.46109947, 277.75405417, 279.54148233, 281.67479356],
        [276.77062676, 281.86684624, 276.79430703, 285.27839165]],

       [[280.93001954, 280.73997403, 280.99760361, 297.22955312],
        [277.46031296, 287.29520299, 280.41611951, 284.72999943],
        [285.12142233, 282.33637365, 284.46942978, 283.83094583]],

       [[275.40347524, 285.72007965, 279.98451064, 288.26664503],
        [277.65057374, 281.52109853, 280.22583217, 280.72883818],
        [287.60271902, 276.53210665, 287.00537175, 281.54459292]]])

## Section 1.2: Wrap the Array: First Attempt

Now we create a basic `DataArray` just by passing our plain `data` as an input:


In [9]:
temperature = xr.DataArray(rand_data)
temperature

<xarray.DataArray (dim_0: 5, dim_1: 3, dim_2: 4)> Size: 480B
array([[[282.9643865 , 282.70292143, 291.51546115, 283.42486548],
        [270.97730145, 289.22798066, 277.52102428, 287.30727676],
        [282.58751063, 286.94690405, 283.28850246, 289.30564317]],

       [[276.71178317, 288.58729864, 275.37034855, 285.25057547],
        [271.41318382, 278.20364763, 280.5031612 , 281.35505081],
        [272.93614756, 282.52331396, 284.16873071, 286.75006634]],

       [[278.78846725, 292.03876694, 285.53074583, 283.29692792],
        [286.46109947, 277.75405417, 279.54148233, 281.67479356],
        [276.77062676, 281.86684624, 276.79430703, 285.27839165]],

       [[280.93001954, 280.73997403, 280.99760361, 297.22955312],
        [277.46031296, 287.29520299, 280.41611951, 284.72999943],
        [285.12142233, 282.33637365, 284.46942978, 283.83094583]],

       [[275.40347524, 285.72007965, 279.98451064, 288.26664503],
        [277.65057374, 281.52109853, 280.22583217, 280.72883818],
        [287.60271902, 276.53210665, 287.00537175, 281.54459292]]])
Dimensions without coordinates: dim_0, dim_1, dim_2

Note two things:

1. Xarray generates some basic dimension names for us (`dim_0`, `dim_1`, `dim_2`). We'll improve this with better names in the next example.
2. Wrapping the numpy array in a `DataArray` gives us a rich display in the notebook! (Try clicking the array symbol to expand or collapse the view)


## Section 1.3: Assign Dimension Names

Much of the power of Xarray comes from making use of named dimensions. So let's add some more useful names! We can do that by passing an ordered list of names using the keyword argument `dims`:


In [10]:
temperature = xr.DataArray(rand_data, dims=["time", "lat", "lon"])
temperature

<xarray.DataArray (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[282.9643865 , 282.70292143, 291.51546115, 283.42486548],
        [270.97730145, 289.22798066, 277.52102428, 287.30727676],
        [282.58751063, 286.94690405, 283.28850246, 289.30564317]],

       [[276.71178317, 288.58729864, 275.37034855, 285.25057547],
        [271.41318382, 278.20364763, 280.5031612 , 281.35505081],
        [272.93614756, 282.52331396, 284.16873071, 286.75006634]],

       [[278.78846725, 292.03876694, 285.53074583, 283.29692792],
        [286.46109947, 277.75405417, 279.54148233, 281.67479356],
        [276.77062676, 281.86684624, 276.79430703, 285.27839165]],

       [[280.93001954, 280.73997403, 280.99760361, 297.22955312],
        [277.46031296, 287.29520299, 280.41611951, 284.72999943],
        [285.12142233, 282.33637365, 284.46942978, 283.83094583]],

       [[275.40347524, 285.72007965, 279.98451064, 288.26664503],
        [277.65057374, 281.52109853, 280.22583217, 280.72883818],
        [287.60271902, 276.53210665, 287.00537175, 281.54459292]]])
Dimensions without coordinates: time, lat, lon

This is already an improvement over a NumPy array because we have names for each of the dimensions (or axes). Even better, we can associate arrays representing the values for the coordinates for each of these dimensions with the data when we create the `DataArray`. We'll see this in the next example.


# Section 2: Create a `DataArray` with Named Coordinates

## Section 2.1: Make Time and Space Coordinates

Here we will use [Pandas](https://foundations.projectpythia.org/core/pandas.html) to create an array of [datetime data](https://foundations.projectpythia.org/core/datetime.html), which we will then use to create a `DataArray` with a named coordinate `time`.


In [11]:
times_index = pd.date_range("2018-01-01", periods=5)
times_index

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

We'll also create arrays to represent sample longitude and latitude:


In [12]:
lons = np.linspace(-120, -60, 4)
lats = np.linspace(25, 55, 3)

### Section 2.1.1: Initialize the `DataArray` with Complete Coordinate Info

When we create the `DataArray` instance, we pass in the arrays we just created:


In [13]:
temperature = xr.DataArray(
    rand_data, coords=[times_index, lats, lons], dims=["time", "lat", "lon"]
)
temperature

<xarray.DataArray (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[282.9643865 , 282.70292143, 291.51546115, 283.42486548],
        [270.97730145, 289.22798066, 277.52102428, 287.30727676],
        [282.58751063, 286.94690405, 283.28850246, 289.30564317]],

       [[276.71178317, 288.58729864, 275.37034855, 285.25057547],
        [271.41318382, 278.20364763, 280.5031612 , 281.35505081],
        [272.93614756, 282.52331396, 284.16873071, 286.75006634]],

       [[278.78846725, 292.03876694, 285.53074583, 283.29692792],
        [286.46109947, 277.75405417, 279.54148233, 281.67479356],
        [276.77062676, 281.86684624, 276.79430703, 285.27839165]],

       [[280.93001954, 280.73997403, 280.99760361, 297.22955312],
        [277.46031296, 287.29520299, 280.41611951, 284.72999943],
        [285.12142233, 282.33637365, 284.46942978, 283.83094583]],

       [[275.40347524, 285.72007965, 279.98451064, 288.26664503],
        [277.65057374, 281.52109853, 280.22583217, 280.72883818],
        [287.60271902, 276.53210665, 287.00537175, 281.54459292]]])
Coordinates:
  * time     (time) datetime64[ns] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lon      (lon) float64 32B -120.0 -100.0 -80.0 -60.0

### Section 2.1.2: Set Useful Attributes

We can also set some attribute metadata, which will help provide clear descriptions of the data. In this case, we can specify that we're looking at 'air_temperature' data and the units are 'Kelvin'.


In [14]:
temperature.attrs["units"] = "Kelvin"
temperature.attrs["standard_name"] = "air_temperature"

temperature

<xarray.DataArray (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[282.9643865 , 282.70292143, 291.51546115, 283.42486548],
        [270.97730145, 289.22798066, 277.52102428, 287.30727676],
        [282.58751063, 286.94690405, 283.28850246, 289.30564317]],

       [[276.71178317, 288.58729864, 275.37034855, 285.25057547],
        [271.41318382, 278.20364763, 280.5031612 , 281.35505081],
        [272.93614756, 282.52331396, 284.16873071, 286.75006634]],

       [[278.78846725, 292.03876694, 285.53074583, 283.29692792],
        [286.46109947, 277.75405417, 279.54148233, 281.67479356],
        [276.77062676, 281.86684624, 276.79430703, 285.27839165]],

       [[280.93001954, 280.73997403, 280.99760361, 297.22955312],
        [277.46031296, 287.29520299, 280.41611951, 284.72999943],
        [285.12142233, 282.33637365, 284.46942978, 283.83094583]],

       [[275.40347524, 285.72007965, 279.98451064, 288.26664503],
        [277.65057374, 281.52109853, 280.22583217, 280.72883818],
        [287.60271902, 276.53210665, 287.00537175, 281.54459292]]])
Coordinates:
  * time     (time) datetime64[ns] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lon      (lon) float64 32B -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          Kelvin
    standard_name:  air_temperature

### Section 2.1.3: Attributes Are Not Preserved by Default!

Notice what happens if we perform a mathematical operaton with the `DataArray`: the coordinate values persist, but the attributes are lost. This is done because it is very challenging to know if the attribute metadata is still correct or appropriate after arbitrary arithmetic operations.

To illustrate this, we'll do a simple unit conversion from Kelvin to Celsius:


In [15]:
temperature_in_celsius = temperature - 273.15
temperature_in_celsius

<xarray.DataArray (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[ 9.8143865 ,  9.55292143, 18.36546115, 10.27486548],
        [-2.17269855, 16.07798066,  4.37102428, 14.15727676],
        [ 9.43751063, 13.79690405, 10.13850246, 16.15564317]],

       [[ 3.56178317, 15.43729864,  2.22034855, 12.10057547],
        [-1.73681618,  5.05364763,  7.3531612 ,  8.20505081],
        [-0.21385244,  9.37331396, 11.01873071, 13.60006634]],

       [[ 5.63846725, 18.88876694, 12.38074583, 10.14692792],
        [13.31109947,  4.60405417,  6.39148233,  8.52479356],
        [ 3.62062676,  8.71684624,  3.64430703, 12.12839165]],

       [[ 7.78001954,  7.58997403,  7.84760361, 24.07955312],
        [ 4.31031296, 14.14520299,  7.26611951, 11.57999943],
        [11.97142233,  9.18637365, 11.31942978, 10.68094583]],

       [[ 2.25347524, 12.57007965,  6.83451064, 15.11664503],
        [ 4.50057374,  8.37109853,  7.07583217,  7.57883818],
        [14.45271902,  3.38210665, 13.85537175,  8.39459292]]])
Coordinates:
  * time     (time) datetime64[ns] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lon      (lon) float64 32B -120.0 -100.0 -80.0 -60.0

We usually wish to keep metadata with our dataset, even after manipulating the data. For example it can tell us what the units are of a variable of interest. So when you perform operations on your data, make sure to check that all the information you want is carried over. If it isn't, you can add it back in following the instructions in the section before this. For an in-depth discussion of how Xarray handles metadata, you can find more information in the Xarray documents [here](http://xarray.pydata.org/en/stable/getting-started-guide/faq.html#approach-to-metadata).


# Section 3: The `Dataset`: a Container for `DataArray`s with Shared Coordinates

Along with `DataArray`, the other key object type in Xarray is the `Dataset`, which is a dictionary-like container that holds one or more `DataArray`s, which can also optionally share coordinates (see docs [here](http://xarray.pydata.org/en/stable/user-guide/data-structures.html#dataset)).

The most common way to create a `Dataset` object is to load data from a file (which we will practice in a later tutorial). Here, instead, we will create another `DataArray` and combine it with our `temperature` data.

This will illustrate how the information about common coordinate axes is used.


## Section 3.1: Create a Pressure `DataArray` Using the Same Coordinates

For our next `DataArry` example, we'll create a random array of `pressure` data in units of hectopascal (hPa). This code mirrors how we created the `temperature` object above.


In [16]:
pressure_data = 1000.0 + 5 * np.random.randn(5, 3, 4)
pressure = xr.DataArray(
    pressure_data, coords=[times_index, lats, lons], dims=["time", "lat", "lon"]
)
pressure.attrs["units"] = "hPa"
pressure.attrs["standard_name"] = "air_pressure"

pressure

<xarray.DataArray (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[1006.75226104, 1001.64521145, 1009.32497277, 1004.37801315],
        [1004.74417146,  997.39163772,  998.71203029, 1000.28228514],
        [1002.87228525, 1003.65349758, 1005.47593309,  999.30582869]],

       [[ 995.11774544,  999.40860458,  996.76525248,  990.96291359],
        [ 999.23630259, 1011.86536326,  991.21281262,  998.65450896],
        [1002.56224127,  993.43342843,  999.30010196,  999.76610453]],

       [[1001.59326759, 1001.08782062, 1002.40769656,  999.74631354],
        [1000.15732777, 1003.41849337, 1003.4416953 ,  993.51868284],
        [1009.08116201, 1005.66181952, 1005.22716348, 1003.00859186]],

       [[ 999.66529125, 1003.11879175, 1000.04837042,  998.01279316],
        [1005.09810042,  996.61015046, 1006.99133983,  997.10234036],
        [1002.97042728,  998.78941424,  998.09692868,  996.15392817]],

       [[1000.57241918, 1002.47193759,  994.91508228, 1003.87755604],
        [ 994.46320649,  996.20529346,  994.95704553,  997.88694435],
        [1003.30709095, 1007.18000948, 1010.4107101 , 1006.6586488 ]]])
Coordinates:
  * time     (time) datetime64[ns] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lon      (lon) float64 32B -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

## Section 3.2: Create a `Dataset` Object

Each `DataArray` in our `Dataset` needs a name!

The most straightforward way to create a `Dataset` with our `temperature` and `pressure` arrays is to pass a dictionary using the keyword argument `data_vars`:


In [17]:
ds = xr.Dataset(data_vars={"Temperature": temperature, "Pressure": pressure})
ds

<xarray.Dataset> Size: 1kB
Dimensions:      (time: 5, lat: 3, lon: 4)
Coordinates:
  * time         (time) datetime64[ns] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat          (lat) float64 24B 25.0 40.0 55.0
  * lon          (lon) float64 32B -120.0 -100.0 -80.0 -60.0
Data variables:
    Temperature  (time, lat, lon) float64 480B 283.0 282.7 291.5 ... 287.0 281.5
    Pressure     (time, lat, lon) float64 480B 1.007e+03 1.002e+03 ... 1.007e+03

Notice that the `Dataset` object `ds` is aware that both data arrays sit on the same coordinate axes.


## Section 3.3: Access Data Variables and Coordinates in a `Dataset`

We can pull out any of the individual `DataArray` objects in a few different ways.

Using the "dot" notation:


In [18]:
ds.Pressure

<xarray.DataArray 'Pressure' (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[1006.75226104, 1001.64521145, 1009.32497277, 1004.37801315],
        [1004.74417146,  997.39163772,  998.71203029, 1000.28228514],
        [1002.87228525, 1003.65349758, 1005.47593309,  999.30582869]],

       [[ 995.11774544,  999.40860458,  996.76525248,  990.96291359],
        [ 999.23630259, 1011.86536326,  991.21281262,  998.65450896],
        [1002.56224127,  993.43342843,  999.30010196,  999.76610453]],

       [[1001.59326759, 1001.08782062, 1002.40769656,  999.74631354],
        [1000.15732777, 1003.41849337, 1003.4416953 ,  993.51868284],
        [1009.08116201, 1005.66181952, 1005.22716348, 1003.00859186]],

       [[ 999.66529125, 1003.11879175, 1000.04837042,  998.01279316],
        [1005.09810042,  996.61015046, 1006.99133983,  997.10234036],
        [1002.97042728,  998.78941424,  998.09692868,  996.15392817]],

       [[1000.57241918, 1002.47193759,  994.91508228, 1003.87755604],
        [ 994.46320649,  996.20529346,  994.95704553,  997.88694435],
        [1003.30709095, 1007.18000948, 1010.4107101 , 1006.6586488 ]]])
Coordinates:
  * time     (time) datetime64[ns] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lon      (lon) float64 32B -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

... or using dictionary access like this:


In [19]:
ds["Pressure"]

<xarray.DataArray 'Pressure' (time: 5, lat: 3, lon: 4)> Size: 480B
array([[[1006.75226104, 1001.64521145, 1009.32497277, 1004.37801315],
        [1004.74417146,  997.39163772,  998.71203029, 1000.28228514],
        [1002.87228525, 1003.65349758, 1005.47593309,  999.30582869]],

       [[ 995.11774544,  999.40860458,  996.76525248,  990.96291359],
        [ 999.23630259, 1011.86536326,  991.21281262,  998.65450896],
        [1002.56224127,  993.43342843,  999.30010196,  999.76610453]],

       [[1001.59326759, 1001.08782062, 1002.40769656,  999.74631354],
        [1000.15732777, 1003.41849337, 1003.4416953 ,  993.51868284],
        [1009.08116201, 1005.66181952, 1005.22716348, 1003.00859186]],

       [[ 999.66529125, 1003.11879175, 1000.04837042,  998.01279316],
        [1005.09810042,  996.61015046, 1006.99133983,  997.10234036],
        [1002.97042728,  998.78941424,  998.09692868,  996.15392817]],

       [[1000.57241918, 1002.47193759,  994.91508228, 1003.87755604],
        [ 994.46320649,  996.20529346,  994.95704553,  997.88694435],
        [1003.30709095, 1007.18000948, 1010.4107101 , 1006.6586488 ]]])
Coordinates:
  * time     (time) datetime64[ns] 40B 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 24B 25.0 40.0 55.0
  * lon      (lon) float64 32B -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          hPa
    standard_name:  air_pressure

We'll return to the `Dataset` object when we start loading data from files in later tutorials today.


# Summary

In this initial tutorial, the `DataArray` and `Dataset` objects were utilized to create and explore synthetic examples of climate data.


# Resources


Code and data for this tutorial is based on existing content from [Project Pythia](https://foundations.projectpythia.org/core/xarray/xarray-intro.html).
